core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from tasks.sitemaps import TaskSitemap

sitemaps = {
    'task': TaskSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'


urlpatterns = [
    path('', views.task_list, name='task_list'),
    path('create/', views.create_task, name='create_task'),
    path('<slug:slug>/', views.task_detail, name='task_detail'),
]

tasks/models.py
from django.db import models
from django.utils.text import slugify
import uuid
from django.contrib.auth.models import User
# Create your models here.


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title + '-' + str(uuid.uuid4())[:4])
        super().save(*args, **kwargs)
        
        return self
    
    def get_absolute_url(self):
        return f'{self.slug}/'
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'
        

tasks/forms.py
from django.forms import ModelForm
from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

tasks/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Task
from .forms import TaskForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
# Create your views here.

def task_list(request):
    tasks_list = Task.objects.all().order_by('-created_at')
    
    page = request.GET.get('page', 1)
    paginator = Paginator(tasks_list, 1)
    tasks = paginator.get_page(page)
    
    # generic = ''
    # campos = ['title', 'description', 'completed']
    # for task in tasks:
    #     for campo in campos:
    #         generic += str('?' + campo + '=' + str(getattr(task, campo)))
        
    
    try:
        tasks = paginator.page(page)
    except PageNotAnInteger:
        tasks = paginator.page(1)
    except EmptyPage:
        tasks = paginator.page(paginator.num_pages)
        
        
    context = {
        'tasks': tasks,
        # 'generic': generic
    }
    
    return render(request, 'tasks/list.html', context)


def task_detail(request, slug):
    task = get_object_or_404(Task, slug=slug)
    return render(request, 'tasks/task_detail.html', {'task': task})


def create_task(request):
    
    context = {}
    form = TaskForm(request.POST or None)
    # sent = False
    context['form'] = form
    
    if request.method == 'POST':
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            
            # sending emails
            
            # post_url = request.build_absolute_uri(task.get_absolute_url())
            # subject = f'{task.user.username} has created a task'
            # message = f'{task.title} - {post_url}'
            # send_mail(subject, message, sender='W2D0V@example.com', recipient=['W2D0V@example.com'])
            # sent = True
            
            return redirect('tasks:task_list')
        context['errors'] = form.errors
    
    return render(request, 'tasks/create.html', context)
    
    

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <title>Title</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body>
        <header>
            <!-- place navbar here -->
        </header>
        <main>

            {% block content %}
            
            
            {% endblock  %}

        </main>
        <footer>
            <!-- place footer here -->
        </footer>
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

templates/includes/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}

            <a href="?page={{page.previous_page_number}}">Previous</a>

        {% endif %}

        <span class="current">

            Page {{page.number}} of {{page.paginator.num_pages}}

            <span>

                {% if page.has_next %}

                    <a href="?page={{page.next_page_number}}">Next</a>
                
                {% endif %}

            </span>
        </span>

    </span>
</div>

templates/tasks/create.html
{% extends '../base.html' %}


{% block content %}


    <form action="" method="POST">


        {% csrf_token %}

        {{form.as_p}}

        <button class="btn btn-success">Create Task</button>

    </form>
    

{% endblock  %}

templates/tasks/list.html
{% extends '../base.html' %}


{% block content %}


    {% if tasks %}

        {% for task in tasks %}
    
            <div class="card">
                <div class="card-body">
                    <h3>{{generic}}</h3>
                    <h4 class="card-title">{{task.title}}</h4>
                    <p class="card-text">{{task.description}}</p>
                </div>
                <div class="card-footer text-muted">
                    <a href="{{task.get_absolute_url}}" class="btn btn-info">
                        See more
                    </a>
                </div>
            </div>
        {% endfor %}


        {% include "../includes/pagination.html" with page=tasks %}

    {% else %}

            <p>You have no tasks...add one  <a href="{% url "tasks:create_task" %}">here</a></p>

    {% endif %}


{% endblock  %}

templates/tasks/task_detail.html
{% extends '../base.html' %}


{% block content %}


    
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">{{task.title}}</h4>
            <p class="card-text">{{task.description}}</p>
        </div>
    </div>
        
    

{% endblock  %}